### ISSUE TITLE
Integration von Circuit in die Applikation

### ISSUE THREAD

**Issue by BenediktSt** [AtosReferenzApplikation/docker-container#44]
# Beschreibung
Circuit als Messenger bietet durch seine Public API großes Potenzial in andere Applikationen integriert und dort im Workflow verankert zu werden.

# Detailliertere Anforderungen
Was ich mir vorstellen kann: Eine Anwendung zur Kundenverwaltung. 
- Grundfunktionalität der Anwendung: anlegen, löschen, bearbeiten und suchen von Kunden. Attribute Name und Adresse
- Kunde hat Kommunikationswege: Email, Telefon, Chat
- Bei den Kommunikationswegen ist die Möglichkeit gegeben, mit einem Button eine Kommunikation mit dem gewählten Kunden anzufangen: Email -> Mailer. Telefon -> Telefonieren mit dem Headset, wahlweise mit Video. Chat -> auch direkt in der Webanwendung.
- Gemeinsame Fallbearbeitung: Der Bearbeiter kann Dokumente zum Kunden ablegen. Hat der Kunde auch einen circuit client oder eine eigene Ansicht der Fachanwendung, kann er auch gemeinsam die Dokumente bearbeiten.

# Potenzielle Erweiterungen
_Wie lässt sich das Projekt potenziell erweitern, wenn noch Zeit vorhanden ist oder in einem Folgeprojekt_

# Offene Punkte
 - [x] grundlegende CRUD Operationen
 - [x] senden einer Mail an den Kunden
 - [x] Kunden eine Nachricht per Cicuit API senden
 - [x] Kunden per Cicuit API anrufen
 - [x] Dokumente per Cicuit API austauschen

# Ziele:
_Welche Ziele werden für den Bearbeiter erreicht? Welche Use Cases für die Abteilung werden damit verdeutlicht?_
